#!/bin/sh
mvn clean package
docker build -t rishit/ExampleClient .
docker rm -f ExampleClient 2>/dev/null || true
docker run -it --name ExampleClient -p 8080:8080 --name ExampleClient rishit/ExampleClient
